### ISSUE TITLE
:Fp word highlights "word" but not "Word"

### ISSUE THREAD

**Issue by baskus** [embear/vim-foldsearch#12]
When I run
```
:Fp word
```
with `let g:foldsearch_highlight=1` I as expected see the `word` highlighted in the folds. However, I also see unhighlighted folds, i.e. folds that are open and show content because they contain text such as `Word`, but where `Word` is not highlighted.

I have this in my _vimrc that might be relevant:
```
set hlsearch
set ignorecase
set smartcase
```
Also I'm on Windows 8.1 and use vim8.

**Comment by embear** [comment]
The used function `matchadd()` does not respect `ignorecase` or `smartcase`. Only (simple) option would be to add an additional `\c` to the folding pattern in the call to `matchadd()` in case `ignorecase` is set. But this might result in an unexpected behavior for users that explicit request case sensitive search using `\C` in the folding pattern. Also this does not respect `smartcase`.
The only correct implementation would be to derive a modified pattern from the folding pattern. Not sure if this is worth the effort and additionally it is very error prone as corner cases might cause trouble.
