### ISSUE TITLE
Allow interactively enter search string

### ISSUE THREAD

**Issue by hupfdule** [embear/vim-foldsearch#15]
It would be nice if there was a command that opens a commandline to enter the string to search for and fold away all the non-matching lines on each keystroke.

fzf.vim's `:BLines` feature is very much what I have in mind, but displays the results in an extra (non-editable) buffer. It would be nice if vim-foldsearch would support this by filtering the actual current buffer.

**Comment by embear** [comment]
That is way beyond the purpose of this plugin.
