### ISSUE TITLE
Allow to hide (or conceal) the folded lines

### ISSUE THREAD

**Issue by hupfdule** [embear/vim-foldsearch#16]
I don't know if this is possible with vim, but it would be nice if the lines that are folded away could be totally hidden. I mean lines like

```
+--617 lines folded  ······················
```

They are a bit distracting if I am actually only interested in the matching lines.
Of course that would not make much sense with a context > 0.

**Comment by embear** [comment]
Sadly this is not possible. Back in the days when I worked on OS/2 I used an editor called [X2](http://www.tangbu.com/) that had the ability to hide not matching lines completely. [X2](http://www.tangbu.com/) made it even possible to block edit the lines with matches.
That inspired me to write the plugin but I never found a way to hide lines completely.
