### ISSUE TITLE
different behavior of execution on command line vs execution in script-function

### ISSUE THREAD

**Issue by kraxli** [embear/vim-foldsearch#17]
Hi 

thanks for this great functionality. Brief question:
I want to show only lines starting with `- [ ]` or multiple `#` (ignoring preceding white spaces). Running 

 `execute 'Fp \V\(\^\s\*\[-+*]\{1}\s[\s]\|\s\*#\{1,6}.\*\)' `

in the command line works perfectly. However, in case I put the same expression in a function, the pattern is *not found*.

Would you know what is going on?

I am using Neovim 0.5 on Linux Mint. 

Many thanks
David

**Comment by embear** [comment]
Sorry for the late answer. Either I don't understand the question correctly or the issue is resolved. Either of the following functions `Foo()` and `Bar()` work for my test file:

```viml
function Foo()
  execute 'Fp \V\(\^\s\*\[-+*]\{1}\s[\s]\|\s\*#\{1,6}.\*\)'
endfunction

function Bar()
  call foldsearch#foldsearch#FoldSearch('\V\(\^\s\*\[-+*]\{1}\s[\s]\|\s\*#\{1,6}.\*\)')
endfunction
```
