### ISSUE TITLE
suggestion for command

### ISSUE THREAD

**Issue by Konfekt** [embear/vim-foldsearch#8]
I am using the command

```
command! -nargs=? -complete=tag -bar Foldsearch execute 'Fp ' . (empty(<q-args>) ? @/ : <q-args>)
```

The only difference to `:Fp` is that `:Foldsearch<CR>` searches for the last search pattern (just as `:Fs`) instead of throwing an error message.  Thus, an amalgam of `:Fs` and `:Fp` at the expense of an error message.

So how about replacing `:Fp` by it?

**Comment by embear** [comment]
`Fp` stands for **F**old**P**attern, `Fs` for **F**old**S**earch. Mixing those makes no sense for the provided plugin. As you wrote it can be added by the user with the mentioned additional code.
