### ISSUE TITLE
Suggestion for FoldToggle

### ISSUE THREAD

**Issue by Konfekt** [embear/vim-foldsearch#9]
How about a command `Ft` that ends the fold search, if there is any, and foldsearches for a pattern otherwise. Here is a draft:

```
command! -nargs=? -complete=tag -bar  Ft call s:foldsearchToggle(<q-args>)

function! s:foldsearchToggle(string)
  let string = empty(a:string) ? @/ : a:string
  if exists('w:foldsearch')
    noautocmd Fe
    syntax on
    normal! zv
    unlet w:foldsearch
  else
    let string=input('/')
    let @/ = (string == '' ? @/ : string)
    Fs
    let w:foldsearch = 1
  endif
endfunction
```

Perhaps best to replace `Fs` by this functionality.

**Comment by Konfekt** [comment]
Thinking further about it, a simple documented variable `w:isFoldsearching` that contains the foldsearch state (active/inactive) would be handy. At the moment, there are lots of them, like `w:foldsearch_context_pre` internally, but all undocumented and subject to change. Nothing to rely on.

**Comment by damianoognissanti** [comment]
I have bound <leader>ff to the function below. This function unfolds all folds if there are any and folds them if there are none. This way it repeats the fold you previously did, whether it was Fs, Fw, FS, etc:

```
function! ToggleFold()
  let view = winsaveview()
  exec 'keepjumps normal! zj'
  if foldclosed('.') > -1 
      exec 'normal! zR'
  else
      exec 'keepjumps normal! zk'
      if foldclosed('.') > -1 
          exec 'normal! zR'
      else 
          exec 'normal! zM'
      endif
  endif
  call winrestview(view)
endfunction
```

**Comment by damianoognissanti** [comment]
Btw, if you have `foldsearch_highlight` turned on and want to remove the highlighting when unfolding you can use the function `Fl` instead of `normal! zM` and `Fe` instead of `normal! zR` above.

**Comment by embear** [comment]
What about the implementation introduced in 15b3c02?

**Comment by damianoognissanti** [comment]
Brilliant! From what I can tell playing around with it, it seems to work perfectly (I noticed the plugin even displays search results under folds (that are there for other reasons) and returns them to their previous folds when toggled). Thanks.

**Comment by damianoognissanti** [comment]
Sorry, I found a minor thing (should I open another issue for that?): If a buffer is not saved the Ft command behaves strangely and the folds aren't removed properly if there are more than one line that get folded. 

For example if it looks like this when folded:
```
hello
+-- 9 lines folded ....
hello
```
it will look like this when unfolded:
```
hello
+-- 9 lines: abcd ....
hello
```
So it shows the start of the content, but it never unfolds it. If the buffer is saved and reopened it works again though.

**Comment by embear** [comment]
I'll take a look at this issue

**Comment by embear** [comment]
@damianoognissanti Sorry, but I can't reproduce this issue. I tried with a unsaved buffer created with `new` and with an file with unsaved changes. All commands `:Fp`, `:Fe`, `:Fl` and `:Ft` seem to work on my side. Can you please provide the exact steps to get the wrong behavior and your foldsearch settings?

**Comment by damianoognissanti** [comment]
@embear Steps to reproduce:
1) Fill buffer with text and make sure you have more than one line with content that will be filtered out
2) Perform any fold search
3) Toggle the fold

Here's an asciinema showing the steps above:
https://asciinema.org/a/DpfCfNbjxYWtJHXNSmYDxCx6c

**Comment by embear** [comment]
@damianoognissanti I tried various things to reproduce the problem over the weekend. But I never was able to get anything like you show in the video with the current version of foldsearch. I also tried older versions of Vim and foldsearch. The only way to get something like your behavior is, when I use an older version of foldsearch that has no `\ft` mapping and some other plugin kicks in.

Please see my recording at https://asciinema.org/a/eYfopV2UQe0D84Jfc4Vt0lxsC

This recording was created with this script:
```viml
call feedkeys(":new\<CR>")
call feedkeys(":on\<CR>")
call feedkeys("ifoo\<ESC>")
call feedkeys("10obar\<ESC>")
call feedkeys("1GyG2P")
call feedkeys("Gofoo\<ESC>1G")
call feedkeys("\\fw")
call feedkeys("\\fe")
call feedkeys(":sleep 500m\<CR>")
call feedkeys("\\fl")
call feedkeys(":sleep 500m\<CR>")
call feedkeys("\\fe")
call feedkeys(":sleep 500m\<CR>")
call feedkeys("\\fl")
call feedkeys(":sleep 500m\<CR>")
call feedkeys("\\ft")
call feedkeys(":sleep 500m\<CR>")
call feedkeys("\\ft")
call feedkeys(":sleep 500m\<CR>")
call feedkeys(":Ft\<CR>")
call feedkeys(":sleep 500m\<CR>")
call feedkeys(":Ft\<CR>")
call feedkeys(":sleep 3\<CR>")
call feedkeys(":qa!\<CR>")
```

Can you please make sure that you are using the latest version of foldsearch and try the above script with the command `vim -c ':so /tmp/feed.vim'`? Can you also please check that no other mapping is shadowing the `\ft` with the command `:nmap \ft`?
As long as I'm not able to reproduce the issue it is really hard to find the problem.

**Comment by damianoognissanti** [comment]
I pulled the latest version* and it still doesn't work. It doesn't work with the feed.vim either and nmap \ft returns "No mapping found". I tried switching terminal emulator, but it's still the same...

I noticed though that if I unfold the folds with zr a two times or more (i.e. toggle fold, press zr, repeat) it starts working...

This is tested on NixOS, so it can be something strange going on here that I don't understand... I will test on another distro too and report back.


*   15b3c02..4f72fb1  main       -> origin/main
Updating 15b3c02..4f72fb1

**Comment by damianoognissanti** [comment]
I tested on gentoo and arch and got the same result. One thing that struck me though is that I don't use a package manager to install plugins, I just git clone them into the correct folder, for example:

`git clone https://github.com/embear/vim-foldsearch ~/.config/nvim/pack/plugins/start/vim-foldsearch`

Can this be an issue?

**Comment by damianoognissanti** [comment]
I tested to remove my config and install it on neovim with lazy.nvim and it's still the same... Very odd... I have no keybindings or anything, I just use :Fw and :Ft to test it, but still it just fails.

**Comment by embear** [comment]
I finally managed to reproduce the problem! There must be some problem/issue with my folding settings of vim. I hope I can find and resolve the problem soon. @damianoognissanti, thank you very much for your effort so far!

**Comment by embear** [comment]
I think I found and fixed the problem in commit c038bc37340d. For unnamed buffers the `mkview` command of Vim, which I use to store the original folding state, does not store manual folds and also does clean all existing folds on restoring the view with `loadview`. This was shadowed on my side with setting `foldlevelstart` to 99.
Could you please give it a try?

**Comment by damianoognissanti** [comment]
Everything works perfectly now. Thank you so much @embear and sorry for ruining your weekend, hope you had time to relax a bit too... :-)

**Comment by embear** [comment]
Good news, thanks for testing. Don't worry about the weekend, the weather was terrible anyway.
I think I'll let this version mature for a few more days and then create a new release.
